services:
  db:
    image: postgres:latest
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  test_db:
    image: postgres:latest
    volumes:
      - ./tmp/test_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    tmpfs:
      - /tmp/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    command: >
       bash -c
       "bundle exec rails db:create &&
       bundle exec rails db:migrate &&
       bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    environment:
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      NODE_OPTIONS: --openssl-legacy-provider

  rspec:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    environment:
      RAILSENV: test
      TEST_HOSTNAME: test_db
    command: >
      bash -c
      "bundle exec rails db:create &&
      bundle exec rails db:migrate &&
      bundle exec spring server"
    volumes:
      - .:/app
    depends_on:
      - test_db


  # webpacker:
  #   build: .
  #   command: ./bin/webpack-dev-server
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "3035:3035"
  #   depends_on:
  #     - web
  front:
    build:
      context: .
      dockerfile: docker/front/Dockerfile
    command: >
      sh -c
      "yarn install &&
      yarn dev"
    volumes:
      - ./front:/app
      - node_modules:/app/node_modules
    env_file:
      - ./front/.env
    depends_on:
      - app
    ports:
      - "8080:8080"

volumes:
  node_modules:
